### ISSUE TITLE
So its not a Linked-list based chaining hashtable

### ISSUE THREAD

**Issue by ShareCat** [nomemory/chained-hash-table-c#1]
I found that you are replacing the value when collisions happens
Check this code:

// Key already exists
// We need to update the value
hash->val_ops.free(crt->val, hash->val_ops.arg);
crt->val = v ? hash->val_ops.cp(v, hash->val_ops.arg) : 0;

**Comment by nomemory** [comment]
Hey thanks for spotting this. At the beginning of the next week I will try to have a look on the problem and comeback with an answer.

**Comment by ShareCat** [comment]
> Hey thanks for spotting this. At the beginning of the next week I will try to have a look on the problem and comeback with an answer.

You can check this project: 
https://github.com/larsendt/hashtable

**Comment by nomemory** [comment]
@ShareCat 

```
    crt = ch_hash_get_node(hash, k);
    if (crt) {
        // Key already exists
        // We need to update the value
        hash->val_ops.free(crt->val, hash->val_ops.arg);
        crt->val = v ? hash->val_ops.cp(v, hash->val_ops.arg) : 0;
```

The function `ch_hash_get_node(hash, k)` checks if the exact key exists. This is not only a collision, as the function checks if the value and the hash are equal. 

So, in this case, we have to replace the value corresponding to the key.

I don't think this is a bug.

**Comment by ShareCat** [comment]
> @ShareCat
> 
> ```
>     crt = ch_hash_get_node(hash, k);
>     if (crt) {
>         // Key already exists
>         // We need to update the value
>         hash->val_ops.free(crt->val, hash->val_ops.arg);
>         crt->val = v ? hash->val_ops.cp(v, hash->val_ops.arg) : 0;
> ```
> 
> The function `ch_hash_get_node(hash, k)` checks if the exact key exists. This is not only a collision, as the function checks if the value and the hash are equal.
> 
> So, in this case, we have to replace the value corresponding to the key.
> 
> I don't think this is a bug.

**Comment by ShareCat** [comment]
> @ShareCat
> 
> ```
>     crt = ch_hash_get_node(hash, k);
>     if (crt) {
>         // Key already exists
>         // We need to update the value
>         hash->val_ops.free(crt->val, hash->val_ops.arg);
>         crt->val = v ? hash->val_ops.cp(v, hash->val_ops.arg) : 0;
> ```
> 
> The function `ch_hash_get_node(hash, k)` checks if the exact key exists. This is not only a collision, as the function checks if the value and the hash are equal.
> 
> So, in this case, we have to replace the value corresponding to the key.
> 
> I don't think this is a bug.

HI, thank you for your reply.
I am not saying that its a bug, i am just saying its not a Linked-list based chaining hashtable, a Linked-list based chaining hashtable can save both values when there is a collisions happens between this two key-values.
U can check this project: https://github.com/larsendt/hashtable, it can save both values when a collisions happens.

**Comment by WangShuoran** [comment]
> > @ShareCat
> > ```
> >     crt = ch_hash_get_node(hash, k);
> >     if (crt) {
> >         // Key already exists
> >         // We need to update the value
> >         hash->val_ops.free(crt->val, hash->val_ops.arg);
> >         crt->val = v ? hash->val_ops.cp(v, hash->val_ops.arg) : 0;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The function `ch_hash_get_node(hash, k)` checks if the exact key exists. This is not only a collision, as the function checks if the value and the hash are equal.
> > So, in this case, we have to replace the value corresponding to the key.
> > I don't think this is a bug.
> 
> HI, thank you for your reply. I am not saying that its a bug, i am just saying its not a Linked-list based chaining hashtable, a Linked-list based chaining hashtable can save both values when there is a collisions happens between this two key-values. U can check this project: https://github.com/larsendt/hashtable, it can save both values when a collisions happens.

I think you are right. This is not an usually Hash table. Because it can not save both values when a collisions happens!
